
#set( $dockerRegistry = '${DOCKER_REGISTRY:-registry.docker.local}' )
#set( $dockerImageTag = '${VERSION:-latest}' )
#set( $eurekaClientServiceurlDefaultzone = '${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://user:user_pass@oss-eureka.local:8761/eureka/}' )
#set( $eurekaInstanceHostnamePrefix = '${EUREKA_INSTANCE_HOSTNAME:-' )
#set( $eurekaInstanceNonsecureport = '${EUREKA_INSTANCE_NONSECUREPORT:-8080}' )
#set( $serverPort = '${SERVER_PORT:-8080}' )
#set( $springProfilesActive = '${ENV:-development}.env' )

version: '2.1'
services:
  admin:
    image: $dockerRegistry/${artifactId}:$dockerImageTag
    restart: always
    command: []
    container_name: $eurekaInstanceHostnamePrefix${artifactId}.local}
    hostname: $eurekaInstanceHostnamePrefix${artifactId}.local}
    ports:
    - "$eurekaInstanceNonsecureport:$serverPort"
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=$eurekaClientServiceurlDefaultzone
    - EUREKA_INSTANCE_HOSTNAME=$eurekaInstanceHostnamePrefix${artifactId}.local}
    - SERVER_PORT=$serverPort
    - SPRING_PROFILES_ACTIVE=$springProfilesActive
    volumes:
    - ${artifactId}-volume:/root/data
    - ${artifactId}-volume:/tmp
    external_links:
    - oss-eureka.local:oss-eureka.local
    - oss-configserver.local:oss-configserver.local

volumes:
  ${artifactId}-volume: {}

networks:
  default:
    external:
      name: oss-network
